/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Tactical_Gamer (https://sketchfab.com/Tactical_Beard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/roman-centurion-armor-d0c6de99f16c49f386a9f8d7c3120dec
Title: Roman Centurion Armor
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Roman_centurion_armor(props) {
  const { nodes, materials } = useGLTF("/roman_centurion_armor.glb");
  return (
    <group scale={2} position={[4, 7.8, -2.5]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.material}
          />
          {/* arms */}
          <group rotation={[-0.5, 0, 0]} position={[0, 0, 0]}>
            <mesh
              geometry={nodes.defaultMaterial_4.geometry}
              material={materials.material}
            />
          </group>
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_9.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
