/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: deandrade (https://sketchfab.com/deandrade)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/roman-legionaire-67e5ec5bd3784483806763dfe1cc848b
Title: Roman Legionaire
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Roman_Legionaire(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[1694.95, 932.93, -1007.15]}
        rotation={[0, 0.15, 0]}
        scale={37.26}
      >
        <group position={[-21.36, 71.39, 18.89]} rotation={[0, 0.33, 0]}>
          <mesh
            geometry={nodes.Pilum_Steel_Rust_0.geometry}
            material={materials.Steel_Rust}
          />
          <mesh
            geometry={nodes.Zylinder_1_2_SkinTorso_0.geometry}
            material={materials["2_SkinTorso"]}
            position={[0.02, -34.19, 0.03]}
            scale={[0.1, 1.14, 0.1]}
          />
          <mesh
            geometry={nodes.Zylinder_Steel_Rust_0.geometry}
            material={materials.Steel_Rust}
            position={[0.02, 11.65, 0.03]}
            scale={[0.1, 1.14, 0.1]}
          />
          <mesh
            geometry={nodes.Pyramide_1_Steel_Rust_0.geometry}
            material={materials.Steel_Rust}
            position={[-0.01, 28.89, 0.01]}
            scale={[0.16, 0.51, 0.18]}
          />
        </group>
        <group position={[-13.38, 25.89, -6.84]} rotation={[0.38, -0.17, 0.02]}>
          <mesh
            geometry={nodes.scabbard_Bronze_0.geometry}
            material={materials.Bronze}
          />
          <mesh
            geometry={nodes.scabbard_Leather_0.geometry}
            material={materials.Leather}
          />
          <mesh
            geometry={nodes.GLADIUS_blade_steel_0.geometry}
            material={materials.steel}
          />
          <mesh
            geometry={nodes.pommel_nut_bronze_0.geometry}
            material={materials.bronze}
          />
          <mesh
            geometry={nodes.pommel_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            geometry={nodes.grip_steel_0.geometry}
            material={materials.steel}
          />
          <mesh
            geometry={nodes.crossguard_steel_0.geometry}
            material={materials.steel}
          />
          <mesh
            geometry={nodes.crossguard_wood_0.geometry}
            material={materials.wood}
          />
          <mesh
            geometry={nodes.ring4_Bronze_0.geometry}
            material={materials.Bronze}
          />
          <mesh
            geometry={nodes.ring3_Bronze_0.geometry}
            material={materials.Bronze}
          />
          <mesh
            geometry={nodes.ring1_Bronze_0.geometry}
            material={materials.Bronze}
          />
          <mesh
            geometry={nodes.ring2_Bronze_0.geometry}
            material={materials.Bronze}
          />
        </group>
        <group position={[17.11, 0, 10.3]} rotation={[0, 1.36, 0]}>
          <mesh
            geometry={nodes.Scutum_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            geometry={nodes.ShieldFront_Shield_Front_0.geometry}
            material={materials.Shield_Front}
          />
          <mesh
            geometry={nodes.ShieldBack_Shield_Back_0.geometry}
            material={materials.Shield_Back}
          />
          <mesh
            geometry={nodes.Bracing_Bracing_0.geometry}
            material={materials.Bracing}
          />
          <mesh
            geometry={nodes.Boss_Bronze_0.geometry}
            material={materials.Bronze_0}
          />
        </group>
        <group position={[0, -6.67, 0]}>
          <mesh
            geometry={nodes.Balteus_leather_leather_0.geometry}
            material={materials.leather}
          />
          <mesh
            geometry={nodes.Bronze_Bronze_0.geometry}
            material={materials.Bronze_0}
          />
          <mesh
            geometry={nodes.TinnedBronze_TinnedBronze_0.geometry}
            material={materials.TinnedBronze}
          />
          <mesh
            geometry={nodes.LeatherEdge_balteus_LeatherEdge_balteus_0.geometry}
            material={materials.LeatherEdge_balteus}
          />
          <mesh
            geometry={
              nodes.LeatherInterior_balteus_LeatherInterior_balteus_0.geometry
            }
            material={materials.LeatherInterior_balteus}
          />
        </group>
        <group position={[-0.22, 0, 0]}>
          <mesh
            geometry={nodes["Leather_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
          />
          <mesh
            geometry={nodes["rCollar_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[0.88, -2.05, 4.17]}
            rotation={[0, 0, 0.05]}
          />
          <mesh
            geometry={nodes["rShldrPlate1_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[8.73, 2.13, 4.08]}
            rotation={[0, 0, 0.15]}
          />
          <mesh
            geometry={nodes["rShldrPlate2_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[9.07, 2.51, 4.2]}
            rotation={[0, 0, 0.15]}
          />
          <mesh
            geometry={nodes["rShldr_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[18.14, 6.39, 4.56]}
            rotation={[0, 0, 0.28]}
          />
          <mesh
            geometry={nodes["lShldr_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[-23.34, 1.2, 3.77]}
            rotation={[0, 0, -0.23]}
          />
          <mesh
            geometry={nodes["lShldrPlate2_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[-18.1, -0.67, 3.77]}
            rotation={[0, 0, -0.15]}
          />
          <mesh
            geometry={nodes["lShldrPlate1_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[-17.55, -0.76, 3.77]}
            rotation={[0, 0, -0.15]}
          />
          <mesh
            geometry={nodes["lCollar_metall-dark_0"].geometry}
            material={materials["metall-dark"]}
            position={[-10.81, -2.53, 3.77]}
            rotation={[0, 0, -0.06]}
          />
        </group>
        <mesh
          geometry={nodes["Bronze_loricasegmentata_metall-dark_0"].geometry}
          material={materials["metall-dark"]}
        />
        <mesh
          geometry={nodes.TUNICA_Fabric_tunic1_0.geometry}
          material={materials.tunic1}
        />
        <mesh
          geometry={nodes.WaistBand_tunic1_0.geometry}
          material={materials.tunic1}
        />
        <mesh
          geometry={nodes.TrimWaistband_tunic1_0.geometry}
          material={materials.tunic1}
        />
        <mesh
          geometry={nodes.TrimWaist_shield_0.geometry}
          material={materials.shield}
          position={[0, 1.67, 0.34]}
        />
        <mesh
          geometry={nodes.TrimNeck_leather_0.geometry}
          material={materials.leather}
        />
        <mesh
          geometry={nodes.Boxers_tunic1_0.geometry}
          material={materials.tunic1}
        />
        <mesh
          geometry={nodes.tunic_tunic1_0.geometry}
          material={materials.tunic1}
          position={[0, -6.76, 0]}
        />
        <mesh
          geometry={nodes["Coolus_Steel_metall-dark_0"].geometry}
          material={materials["metall-dark"]}
        />
        <mesh
          geometry={nodes.NeckRidges_steel_0.geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes.Bronze_helmet_Bronze_helmet_0.geometry}
          material={materials.Bronze_helmet}
        />
        <mesh
          geometry={nodes.Eyebrow_Bronze_0.geometry}
          material={materials.Bronze_0}
        />
        <mesh
          geometry={nodes.LeatherEdge_rCaliga_LeatherInterior_0.geometry}
          material={materials.LeatherInterior}
        />
        <mesh
          geometry={nodes.FootBed_rCaliga_LeatherInterior_0.geometry}
          material={materials.LeatherInterior}
        />
        <mesh
          geometry={nodes.SoleBottom_rCaliga_steel_0.geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes.SoleEdge_rCaliga_Mat1_0.geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          geometry={nodes.LeatherExterior_rCaliga_Mat1_0.geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          geometry={nodes.LeatherInterior_rCaliga_LeatherInterior_0.geometry}
          material={materials.LeatherInterior}
        />
        <mesh
          geometry={nodes.LeatherEdge_lCaligae_LeatherInterior_0.geometry}
          material={materials.LeatherInterior}
        />
        <mesh
          geometry={nodes.FootBed_LeatherInterior_0.geometry}
          material={materials.LeatherInterior}
        />
        <mesh
          geometry={nodes.SoleBottom_steel_0.geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes.SoleEdge_Mat1_0.geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          geometry={nodes.LeatherExterior_Mat1_0.geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          geometry={nodes.LeatherInterior_LeatherInterior_0.geometry}
          material={materials.LeatherInterior}
        />
        <mesh
          geometry={nodes["2_SkinHead_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["2_SkinNeck_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["7_Tear_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["5_Lacrimal_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["1_Nostril_1_Nostril_0"].geometry}
          material={materials["1_Nostril"]}
        />
        <mesh
          geometry={nodes["1_SkinFace_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["1_Lip_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["4_InnerMouth_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["4_Tongue_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["5_Pupil_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["5_Iris_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["5_Cornea_5_Cornea_0"].geometry}
          material={materials["5_Cornea"]}
        />
        <mesh
          geometry={nodes["2_SkinHip_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["3_Toenail_3_SkinForearm_0"].geometry}
          material={materials["3_SkinForearm"]}
        />
        <mesh
          geometry={nodes["3_Fingernail_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["3_SkinHand_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["3_SkinLeg_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["3_SkinForearm_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["2_Nipple_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["2_SkinTorso_flesh_0"].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes["3_SkinArm_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["4_Gums_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["4_Teeth_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["5_Sclera_steel_0"].geometry}
          material={materials.steel}
        />
        <mesh
          geometry={nodes["3_SkinFoot_flesh_0"].geometry}
          material={materials.flesh}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
