/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: IRONHIDE161 (https://sketchfab.com/IRONHIDE161)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/roman-armory-b8522f5c2c5d4d41a552fc64c2319e5e
Title: Roman Armory
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RomanGear(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group scale={0.0045} position={[-4, 6.2, -2]} {...props} dispose={null}>
      <group
        position={[-18.68, 284.62, 92.31]}
        rotation={[1.29, -0.1, -0.15]}
        scale={100}
      >
        <group position={[0, 0, 0.4]}>
          <mesh
            geometry={nodes.Sphere001_wood_dark_0.geometry}
            material={materials.wood_dark}
          />
          <mesh
            geometry={nodes.Sphere002_gold_0.geometry}
            material={materials.gold}
          />
        </group>
        <mesh
          geometry={nodes.Sphere_wood_dark_0.geometry}
          material={materials.wood_dark}
        />
        <mesh
          geometry={nodes.Cylinder_gold_0.geometry}
          material={materials.gold}
          position={[0, 0, -0.23]}
        />
        <mesh
          geometry={nodes.Cube_wood_0.geometry}
          material={materials.wood}
          position={[0, 0, 0.41]}
        />
        <mesh
          geometry={nodes.Cube001_metal_0.geometry}
          material={materials.metal}
          position={[0, 0, 0.4]}
        />
      </group>
      <group
        position={[181.32, 87.44, 22.38]}
        rotation={[-3.1, 0.93, 3.11]}
        scale={100}
      >
        <mesh
          geometry={nodes.Circle001_metal_hilt_0.geometry}
          material={materials.metal_hilt}
        />
        <mesh
          geometry={nodes.Cube002_metal_blade_0.geometry}
          material={materials.metal_blade}
          position={[0, 0, -1]}
        />
      </group>
      <group
        position={[-198.89, 164.39, 157.11]}
        rotation={[-1.7, 0.07, -0.51]}
        scale={100}
      >
        <mesh
          geometry={nodes.Cube003_metal_shield_0.geometry}
          material={materials.metal_shield}
        />
        <mesh
          geometry={nodes.Circle004_gold_0.geometry}
          material={materials.gold}
          position={[0.3, -0.03, 0.42]}
          rotation={[1.57, 0.09, 0]}
        />
        <mesh
          geometry={nodes.Circle002_gold_0.geometry}
          material={materials.gold}
          position={[0.93, 0.4, 0]}
          rotation={[Math.PI / 2, 0.41, 0]}
        />
      </group>
      <group
        position={[-185.63, 161.6, 133.81]}
        rotation={[-0.17, -0.51, -0.08]}
        scale={100}
      >
        <mesh
          geometry={nodes.Plane004_leather_0.geometry}
          material={materials.leather}
        />
        <mesh
          geometry={nodes.Plane004_shield_0.geometry}
          material={materials.shield}
        />
      </group>
      <group
        position={[-77.41, -64.58, 299.7]}
        rotation={[-1.83, -0.08, 1.85]}
        scale={100}
      >
        <mesh
          geometry={nodes.Cylinder002_black_metal_0.geometry}
          material={materials.black_metal}
        />
        <mesh
          geometry={nodes.Cylinder003_black_metal_0.geometry}
          material={materials.black_metal}
          position={[0, -0.07, 0.05]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
      </group>
      <group
        position={[-124.19, 523.76, 140.65]}
        rotation={[-1.83, -0.08, 0.28]}
        scale={100}
      >
        <mesh
          geometry={nodes.Cube005_metal_spear_0.geometry}
          material={materials.metal_spear}
        />
        <mesh
          geometry={nodes.Cube005_black_metal_0.geometry}
          material={materials.black_metal}
        />
      </group>
      <group
        position={[26.58, 95.74, 15.45]}
        rotation={[-1.53, -0.03, -0.25]}
        scale={100}
      >
        <mesh
          geometry={nodes.Cube008_wood_spear_0.geometry}
          material={materials.wood_spear}
        />
        <mesh
          geometry={nodes.Cube008_wood_dark_0.geometry}
          material={materials.wood_dark}
        />
        <mesh
          geometry={nodes.Cube008_wood_gold_0.geometry}
          material={materials.wood_gold}
        />
      </group>
      <mesh
        geometry={nodes.Plane001_shield_dirty_0.geometry}
        material={materials.shield_dirty}
        position={[-136.23, 145.73, 47.56]}
        rotation={[-0.17, -0.51, -0.08]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane002_gold_0.geometry}
        material={materials.gold}
        position={[-182.02, 159.36, 127.61]}
        rotation={[-0.17, -0.51, -0.08]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane003_shield_0.geometry}
        material={materials.shield}
        position={[-190.61, 161.92, 142.64]}
        rotation={[-0.17, -0.51, -0.08]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder001_wood_spear_0.geometry}
        material={materials.wood_spear}
        position={[-99.78, 216.81, 223.63]}
        rotation={[-1.83, -0.08, 0.28]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCircle_fabric_0.geometry}
        material={materials.fabric}
        position={[-112.82, 380.8, 179.3]}
        rotation={[-1.83, -0.08, 0.28]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere003_black_metal_0.geometry}
        material={materials.black_metal}
        position={[-117.2, 435.84, 164.42]}
        rotation={[-1.83, -0.08, -1.29]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube004_wood_spear_0.geometry}
        material={materials.wood_spear}
        position={[-120.14, 472.89, 154.4]}
        rotation={[-1.83, -0.08, -2.87]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane005_black_metal_0.geometry}
        material={materials.black_metal}
        position={[-129.55, 502.24, 148.5]}
        rotation={[2.66, 1.29, 1.76]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube007_wood_dark_0.geometry}
        material={materials.wood_dark}
        position={[29.64, 96.35, 3.64]}
        rotation={[-1.53, -0.03, -0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Circle003_metal_shield_0.geometry}
        material={materials.metal_shield}
        position={[21.14, 86.49, 37.06]}
        rotation={[-0.93, -0.09, -0.39]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube009_crossbow_fabric_0.geometry}
        material={materials.crossbow_fabric}
        position={[-1.91, 95.3, 8.41]}
        rotation={[-1.51, 0.02, 1.24]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube010_crossbow_fabric_0.geometry}
        material={materials.crossbow_fabric}
        position={[-7.39, 94.89, 6.45]}
        rotation={[-1.53, -0.03, 1.24]}
        scale={100}
      />
      <mesh
        geometry={nodes.Box002_metal_spear_0.geometry}
        material={materials.metal_spear}
        position={[27.35, 96.12, -51.26]}
        rotation={[3.05, -1.35, -1.71]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder004_metal_hilt_0.geometry}
        material={materials.metal_hilt}
        position={[56.6, 103.87, -148.31]}
        rotation={[-0.04, 1.28, -1.47]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder005_metal_shield_0.geometry}
        material={materials.metal_shield}
        position={[26.11, 111.32, 16.13]}
        rotation={[-1.53, -0.03, -0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Circle006_rope_0.geometry}
        material={materials.rope}
        position={[17.5, 96.84, -15.65]}
        rotation={[-1.53, -0.03, 1.32]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder006_crossbow_fabric_0.geometry}
        material={materials.crossbow_fabric}
        position={[37.36, 97.23, -26.11]}
        rotation={[-0.07, 1.32, -1.45]}
        scale={100}
      />
      <mesh
        geometry={nodes.Circle007_metal_blade_0.geometry}
        material={materials.metal_blade}
        position={[21.24, 99.53, 35.31]}
        rotation={[-0.87, 0, -0.19]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder007_wood_dark_0.geometry}
        material={materials.wood_dark}
        position={[48.98, 111.83, -71.84]}
        rotation={[-0.07, 1.32, -1.09]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder008_metal_hilt_0.geometry}
        material={materials.metal_hilt}
        position={[28.7, 107.86, -59.61]}
        rotation={[-0.07, 1.32, -1.45]}
        scale={100}
      />
      <mesh
        geometry={nodes.BezierCurve002_leather_crossbow_0.geometry}
        material={materials.leather_crossbow}
        position={[-124.17, 104.69, -67.15]}
        rotation={[0.02, 0, 0.12]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube015_metal_hilt_0.geometry}
        material={materials.metal_hilt}
        position={[51.05, 87.69, -78.05]}
        rotation={[-1.53, -0.03, -0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane008_metal_blade_0.geometry}
        material={materials.metal_blade}
        position={[51.15, 89.63, -78.56]}
        rotation={[-1.43, -0.09, -0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube016_metal_hilt_0.geometry}
        material={materials.metal_hilt}
        position={[58.69, 106.45, -108.76]}
        rotation={[-1.53, -0.03, -0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube017_metal_hilt_0.geometry}
        material={materials.metal_hilt}
        position={[60.58, 106.83, -116.06]}
        rotation={[-1.53, -0.03, -0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder011_rope_0.geometry}
        material={materials.rope}
        position={[29.64, 96.37, 3.64]}
        rotation={[-1.53, -0.03, -1.76]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube020_crossbow_fabric_0.geometry}
        material={materials.crossbow_fabric}
        position={[-13.4, 94.83, 3.68]}
        rotation={[-1.53, -0.03, 1.31]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube018_crossbow_fabric_0.geometry}
        material={materials.crossbow_fabric}
        position={[-95.47, 107.69, -66.72]}
        rotation={[-1.53, -0.03, 1.6]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube019_crossbow_fabric_0.geometry}
        material={materials.crossbow_fabric}
        position={[-100.2, 106.7, -66.48]}
        rotation={[-1.53, -0.03, 1.6]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube006_Material_0.geometry}
        material={materials.Material}
        position={[-4.28, -14.52, -6.98]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
